<?php

/**
 * This is the model base class for the table "{{video_comment}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VideoComment".
 *
 * Columns in table "{{video_comment}}" available as properties of the model,
 * followed by relations of table "{{video_comment}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $video_id
 * @property string $contents
 *
 * @property Video $video
 * @property XfUser $user
 */
abstract class BaseVideoComment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{video_comment}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VideoComment|VideoComments', $n);
	}

	public static function representingColumn() {
		return 'contents';
	}

	public function rules() {
		return array(
			array('user_id, video_id, contents', 'required'),
			array('user_id, video_id', 'numerical', 'integerOnly'=>true),
			array('id, user_id, video_id, contents', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'video' => array(self::BELONGS_TO, 'Video', 'video_id'),
			'user' => array(self::BELONGS_TO, 'XfUser', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'video_id' => null,
			'contents' => Yii::t('app', 'Contents'),
			'video' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('video_id', $this->video_id);
		$criteria->compare('contents', $this->contents, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}