<?php

/**
 * This is the model base class for the table "{{slide_manager}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SlideManager".
 *
 * Columns in table "{{slide_manager}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $title
 * @property string $url
 * @property string $image
 * @property integer $pos
 * @property integer $status
 *
 */
abstract class BaseSlideManager extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{slide_manager}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SlideManager|SlideManagers', $n);
	}

	public static function representingColumn() {
		return 'image';
	}

	public function rules() {
		return array(
			array('image', 'required'),
			array('pos, status', 'numerical', 'integerOnly'=>true),
			array('title, url, image', 'length', 'max'=>255),
			array('title, url, pos, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, url, image, pos, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Tiêu đề'),
			'url' => Yii::t('app', 'Đường dẫn (Url)'),
			'image' => Yii::t('app', 'Ảnh'),
			'pos' => Yii::t('app', 'Vị trí'),
			'status' => Yii::t('app', 'Trạng thái'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('pos', $this->pos);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}