<?php

/**
 * This is the model base class for the table "{{page}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Page".
 *
 * Columns in table "{{page}}" available as properties of the model,
 * followed by relations of table "{{page}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $body
 * @property integer $status
 * @property integer $user_id
 * @property integer $create_time
 * @property integer $update_time
 *
 * @property XfUser $user
 */
abstract class BasePage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{page}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Page|Pages', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('status, user_id, create_time, update_time', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('body', 'safe'),
			array('body, status, user_id, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, body, status, user_id, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'XfUser', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Tiêu đề'),
			'body' => Yii::t('app', 'Nội dung'),
			'status' => Yii::t('app', 'Trạng thái'),
			'user_id' => null,
			'create_time' => Yii::t('app', 'Ngày đăng'),
			'update_time' => Yii::t('app', 'Ngày sửa'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('body', $this->body, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('create_time', $this->create_time);
		$criteria->compare('update_time', $this->update_time);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}