<?php

/**
 * This is the model base class for the table "{{vocabulary}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Vocabulary".
 *
 * Columns in table "{{vocabulary}}" available as properties of the model,
 * followed by relations of table "{{vocabulary}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property Term[] $terms
 */
abstract class BaseVocabulary extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{vocabulary}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Loại danh mục', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>255),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'terms' => array(self::HAS_MANY, 'Term', 'vid'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Tên'),
			'terms' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}