<?php

/**
 * This is the model base class for the table "{{hopam_comment}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HopamComment".
 *
 * Columns in table "{{hopam_comment}}" available as properties of the model,
 * followed by relations of table "{{hopam_comment}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $hopam_id
 * @property string $contents
 * @property integer $status
 *
 * @property Hopam $hopam
 * @property XfUser $user
 */
abstract class BaseHopamComment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{hopam_comment}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HopamComment|HopamComments', $n);
	}

	public static function representingColumn() {
		return 'contents';
	}

	public function rules() {
		return array(
			array('user_id, hopam_id, contents', 'required'),
			array('user_id, hopam_id, status', 'numerical', 'integerOnly'=>true),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, hopam_id, contents, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'hopam' => array(self::BELONGS_TO, 'Hopam', 'hopam_id'),
			'user' => array(self::BELONGS_TO, 'XfUser', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'hopam_id' => null,
			'contents' => Yii::t('app', 'Contents'),
			'status' => Yii::t('app', 'Status'),
			'hopam' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('hopam_id', $this->hopam_id);
		$criteria->compare('contents', $this->contents, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}