<?php

/**
 * This is the model base class for the table "{{term}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Term".
 *
 * Columns in table "{{term}}" available as properties of the model,
 * followed by relations of table "{{term}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $vid
 * @property integer $parent
 *
 * @property Vocabulary $v
 * @property Video[] $videos
 */
abstract class BaseTerm extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{term}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Danh mục', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('vid, parent', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('vid, parent', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, vid, parent', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'v' => array(self::BELONGS_TO, 'Vocabulary', 'vid'),
			'videos' => array(self::HAS_MANY, 'Video', 'term_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Tên'),
			'vid' => null,
			'parent' => Yii::t('app', 'Cấp cha'),
			'v' => null,
			'videos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('vid', $this->vid);
		$criteria->compare('parent', $this->parent);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}