<?php

/**
 * This is the model base class for the table "{{order}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Order".
 *
 * Columns in table "{{order}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $user_id
 * @property string $cost
 * @property string $paid
 * @property integer $create_time
 * @property integer $paid_time
 * @property string $pid
 * @property integer $status
 *
 */
abstract class BaseOrder extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{order}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Order|Orders', $n);
	}

	public static function representingColumn() {
		return 'cost';
	}

	public function rules() {
		return array(
			array('user_id', 'required'),
			array('create_time, paid_time, status', 'numerical', 'integerOnly'=>true),
			array('user_id', 'length', 'max'=>10),
			array('cost, paid', 'length', 'max'=>20),
			array('pid', 'length', 'max'=>255),
			array('cost, paid, create_time, paid_time, pid, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, cost, paid, create_time, paid_time, pid, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(

		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'Mã ĐH'),
			'user_id' => Yii::t('app', 'Thành viên'),
			'cost' => Yii::t('app', 'Tổng tiền'),
			'paid' => Yii::t('app', 'Đã thanh toán'),
			'create_time' => Yii::t('app', 'Ngày mua'),
			'paid_time' => Yii::t('app', 'Ngày thanh toán'),
			'pid' => Yii::t('app', 'Pid'),
			'status' => Yii::t('app', 'Trạng thái'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id, true);
		$criteria->compare('cost', $this->cost, true);
		$criteria->compare('paid', $this->paid, true);
		$criteria->compare('create_time', $this->create_time);
		$criteria->compare('paid_time', $this->paid_time);
		$criteria->compare('pid', $this->pid, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}