<?php

/**
 * This is the model base class for the table "{{student}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Student".
 *
 * Columns in table "{{student}}" available as properties of the model,
 * followed by relations of table "{{student}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $tel
 * @property string $birthday
 * @property integer $class_id
 * @property integer $user_id
 * @property string $comment
 *
 * @property ClassGuitar $class
 */
abstract class BaseStudent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{student}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Học viên', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, email, tel, class_id', 'required'),
			array('class_id, user_id', 'numerical', 'integerOnly'=>true),
			array('name, email, birthday,create_time,pay_time,status', 'length', 'max'=>100),
			array('tel', 'length', 'max'=>25),
			array('comment,create_time,pay_time', 'safe'),
			array('birthday, user_id, comment', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, email, tel, birthday, class_id, user_id, comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'class' => array(self::BELONGS_TO, 'ClassGuitar', 'class_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Họ tên'),
			'email' => Yii::t('app', 'Email'),
			'tel' => Yii::t('app', 'Điện thoại'),
			'birthday' => Yii::t('app', 'Ngày sinh'),
			'class_id' => null,
			'user_id' => Yii::t('app', 'User'),
			'comment' => Yii::t('app', 'Yêu cầu khác'),
			'class' => null,
            'create_time'=>'Ngày đăng ký',
            'pay_time'=>'Ngày nộp học phí'
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('tel', $this->tel, true);
		$criteria->compare('birthday', $this->birthday, true);
		$criteria->compare('class_id', $this->class_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('comment', $this->comment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}