<?php

/**
 * This is the model base class for the table "{{like_hopam}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LikeHopam".
 *
 * Columns in table "{{like_hopam}}" available as properties of the model,
 * followed by relations of table "{{like_hopam}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $hopam_id
 * @property integer $like_time
 *
 * @property Hopam $hopam
 */
abstract class BaseLikeHopam extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{like_hopam}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LikeHopam|LikeHopams', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('user_id, hopam_id', 'required'),
			array('user_id, hopam_id, like_time', 'numerical', 'integerOnly'=>true),
			array('like_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, hopam_id, like_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'hopam' => array(self::BELONGS_TO, 'Hopam', 'hopam_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'hopam_id' => null,
			'like_time' => Yii::t('app', 'Like Time'),
			'hopam' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('hopam_id', $this->hopam_id);
		$criteria->compare('like_time', $this->like_time);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}