<?php

/**
 * This is the model base class for the table "{{training}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Training".
 *
 * Columns in table "{{training}}" available as properties of the model,
 * followed by relations of table "{{training}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $body
 * @property integer $status
 *
 * @property ClassGuitar[] $classGuitars
 */
abstract class BaseTraining extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{training}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Khóa học', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('body', 'safe'),
			array('body, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, body, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'classGuitars' => array(self::HAS_MANY, 'ClassGuitar', 'tid'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Tên'),
			'body' => Yii::t('app', 'Miêu tả'),
			'status' => Yii::t('app', 'Trạng thái'),
			'classGuitars' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('body', $this->body, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}