<?php

/**
 * This is the model base class for the table "{{teacher}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Teacher".
 *
 * Columns in table "{{teacher}}" available as properties of the model,
 * followed by relations of table "{{teacher}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $body
 * @property string $picture
 * @property integer $status
 * @property integer $like_count
 * @property integer $view
 * @property integer $pos
 * @property LikeTeacher[] $likeTeachers
 * @property TeacherPhoto[] $teacherPhotos
 * @property Video[] $videos
 */
abstract class BaseTeacher extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{teacher}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Giáo viên', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name,picture,username', 'required'),
			array('status, like_count,pos', 'numerical', 'integerOnly'=>true),
			array('name, picture,username', 'length', 'max'=>255),
			array('body', 'safe'),
			array('body, picture, status, like_count', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, body, picture, status, like_count', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'likeTeachers' => array(self::HAS_MANY, 'LikeTeacher', 'teacher_id'),
			'likeTeachersCount' => array(self::STAT, 'LikeTeacher', 'teacher_id'),
			'teacherPhotos' => array(self::HAS_MANY, 'TeacherPhoto', 'teacher_id'),
			'videos' => array(self::HAS_MANY, 'Video', 'teacher_id'),
			'videoCount' => array(self::STAT, 'Video', 'teacher_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Họ Tên'),
			'pos' => Yii::t('app', 'Vị trí'),
			'body' => Yii::t('app', 'Miêu tả'),
			'picture' => Yii::t('app', 'Hình ảnh'),
			'status' => Yii::t('app', 'Trạng thái'),
			'like_count' => Yii::t('app', 'Like Count'),
			'username' => Yii::t('app', 'Tài khoản'),
			//'view' => Yii::t('app', 'View'),
			'likeTeachers' => null,
            'likeTeachersCount'=>'Yêu thích',
			'teacherPhotos' => null,
			'videos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('body', $this->body, true);
		$criteria->compare('picture', $this->picture, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('like_count', $this->like_count);
		$criteria->compare('username', $this->username);
		//$criteria->compare('view', $this->view);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}