<?php

/**
 * This is the model base class for the table "{{center}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Center".
 *
 * Columns in table "{{center}}" available as properties of the model,
 * followed by relations of table "{{center}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $body
 * @property integer $province_id
 * @property integer $district_id
 *
 * @property ClassGuitar[] $classGuitars
 */
abstract class BaseCenter extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{center}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Trung tâm', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('province_id, district_id', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('body', 'safe'),
			array('body, province_id, district_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, body, province_id, district_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'classGuitars' => array(self::HAS_MANY, 'ClassGuitar', 'cid'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Tên cơ sở'),
			'body' => Yii::t('app', 'Miêu tả'),
			'province_id' => Yii::t('app', 'Tỉnh/TP'),
			'district_id' => Yii::t('app', 'Quận/Huyện'),
			'classGuitars' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('body', $this->body, true);
		$criteria->compare('province_id', $this->province_id);
		$criteria->compare('district_id', $this->district_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination'=>array(
                'pageSize'=>Yii::app()->params['itemsPerPage'],
            ),
		));
	}
}